"""Create table Product

Revision ID: 0e5bc647e06c
Revises: 19913c324c60
Create Date: 2023-12-14 16:07:35.645377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e5bc647e06c'
down_revision = '19913c324c60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_product',
    sa.Column('idCategory', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nameCategory', sa.String(length=140), nullable=False),
    sa.Column('descCategory', sa.String(length=140), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('idCategory')
    )
    with op.batch_alter_table('category_product', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_category_product_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_category_product_updated_at'), ['updated_at'], unique=False)

    op.create_table('product',
    sa.Column('kode', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nameProduct', sa.String(length=140), nullable=False),
    sa.Column('descProduct', sa.String(length=140), nullable=False),
    sa.Column('price', sa.BigInteger(), nullable=False),
    sa.Column('stock', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('kode')
    )
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_updated_at'), ['updated_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_updated_at'))
        batch_op.drop_index(batch_op.f('ix_product_created_at'))

    op.drop_table('product')
    with op.batch_alter_table('category_product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_category_product_updated_at'))
        batch_op.drop_index(batch_op.f('ix_category_product_created_at'))

    op.drop_table('category_product')
    # ### end Alembic commands ###
