"""Create table CategoryProduct

Revision ID: f0b190a65ac9
Revises: 0e5bc647e06c
Create Date: 2023-12-14 16:10:09.618688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0b190a65ac9'
down_revision = '0e5bc647e06c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category_product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kdProduct', sa.BigInteger(), nullable=True))
        batch_op.create_foreign_key(None, 'product', ['kdProduct'], ['kode'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category_product', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('kdProduct')

    # ### end Alembic commands ###
